import { createTheme } from "@mui/material";

const Theme = createTheme({
  palette: {
    primary: {
      main: "#607d8b",
      light: "#b0bec5",
      dark: "#455a64",
    },
    secondary: {
      main: "#fff59d",
      light: "#ffffcf",
      dark: "#cbc26d",
    },
  },
  typography: {
    fontFamily: "Exo",
    fontSize: 20,
  },
});

const ITEM_HEIGHT = 48;
const ITEM_PADDING_TOP = 8;
const MenuProps = {
  PaperProps: {
    style: {
      maxHeight: ITEM_HEIGHT * 4.5 + ITEM_PADDING_TOP,
      width: 250,
    },
  },
  getContentAnchorEl: null,
  anchorOrigin: {
    vertical: "bottom",
    horizontal: "center",
  },
  transformOrigin: {
    vertical: "top",
    horizontal: "center",
  },
  variant: "menu",
};

const optionsElement = [
  "air",
  "clay",
  "dark",
  "death",
  "earth",
  "fire",
  "holy",
  "ice",
  "light",
  "lightning",
  "magical",
  "metal",
  "oil",
  "physical",
  "poison",
  "rock",
  "stone",
  "thunder",
  "water",
  "wind",
];

const optionsWeakness = [
  "dark",
  "daze",

  "slow movement",
  "lightning",
  "damage from swords",
  "shields element",
  "lightning element",
  "size",
  "polearms",
  "earth",
  "fire",
  "ice",
  "dia",
  "fire spells",
  "stone",
  "poison",
  "holy",
  "wizzard cast",
  "spell",
  "fire elemental weapons",
  "light",
  "water",
  "ground",
  "gravity",
  "launch",

  "wind",

  "piercing",
  "low HP",
  "haste",
  "regen",
  "reflect",
  "drain",
];

const optionsStrength = [
  "fire based attacks",
  "blaster attacks",
  "size",
  "heaviness",
  "attack blockers",
  "spellcast",
  "lightning",
  "speed",
  "normal attack",
  "lunge",
  "tri-attack",
  "pyromania",
  "ram",
  "scream",
  "warsong",
  "vespersong",
  "acute senses",
  "fast",
  "war cry",
  "ochu danse",
  "drink magic",
  "quicksand",
  "earhquake",
  "constrict",
  "sandstorm",
  "body slam",
  "physical attack",
  "gaze attack",
  "mist attack",
  "fire",
  "strike",
  "blaze",
  "icestorm",
  "cura",
  "ice",
  "reflection",
  "wings",
  "immunity to confusion",
  "mighty guard",
  "spell",
  "magic defense",
  "multiple attack sequence",
  "ink blindness",
  "poison gas attack",
  "magic resistance",
  "group attack",
  "fast jump",
  "battle in a pack",
  "wind absorption",
  "defense stat",
  "poison feathers",
  "tail strike",
  "wing flap",
  "self-healing abilities",
  "imune to poison",
  "silence",
  "sleep",
  "stop",
  "slow",
  "berserk",
];

const optionsResistance = [
  "fire",
  "wind",
  "death",
  "alterna",
  "stop",
  "poison",
  "quake",
  "consfuse",
  "paralysis",
  "petrify",
  "darkness",
  "sleep",
  "silence",
  "mind",
  "none",
  "blind",
  "lure",
  "alterna",
  "time",
  "stone",
  "ice",
  "lightning",
  "light",
  "blindness",
  "curse",
  "daze",
  "unknown",
  "water",
  "magic",
  "thunder",
  "earth",
  "slow",
  "imperil",
  "fog",
  "pain",
  "doom",
  "disese",
  "sap",
  "reverse",
  "disable",
  "berserk",
  "damage spikes",
  "float",
];

const optinonsWeapon = [
  "fire-brathing",
  "blaze",
  "thunder",
  "bio",
  "confuse",
  "death",
  "demi",
  "aero",
  "level 5 death",
  "meteor",
  "holy",
  "esuna",
  "blaster",
  "fatal walking over",
  "arms shooting",
  "state of temporary invicibility",
  "magic spell",
  "wings",
  "mandible",
  "sword",
  "platinum sword",
  "bile",
  "lunge",
  "fangs",
  "claws",
  "tentacles",
  "earthquake",
  "gaia drum",
  "earth hammer",
  "earth spellstone",
  "spell flare",
  "maelstrom",
  "spikes",
  "poison",
  "hellfire",
  "inferno",
  "punch",
  "burning strike",
  "meteor strike",
  "paralyzing gaze",
  "trident",
  "flash-freeze",
  "frostwave",
  "bite",
  "breath",
  "kick",
  "magic",
  "plasma storm",
  "dragon claws",
  "thunderbolt",
  "blase",
  "icesotrm",
  "poison gas",
  "spell cycle with fira",
  "dark",
  "hold",
  "paralysis attack",
  "ink",
  "spear",
  "gnaw",
  "blast wave",
  "leech",
  "dagger",
  "firearms",
  "light",
  "slap",
  "divine",
  "aereo",
  "sleep",
  "blind",
  "physical attack",
  "physical damage",
  "magical damage",
];

export {
  Theme,
  MenuProps,
  optionsElement,
  optionsStrength,
  optionsWeakness,
  optionsResistance,
  optinonsWeapon,
};
